[General]
loglevel = info

always-real-ip = *
routing-domain-resolve = true
local-dns-server = 1.1.1.1,8.8.8.8

http-interface = 0.0.0.0
http-port = 8080

socks-interface = 0.0.0.0
socks-port = 1080

dns-server = tcp://127.0.0.1:1088
dns-interface = 127.0.0.1
dns-port = 1088

[Dns]
cloudflare_doh = doh, cdnjs.com, 443, domain=cloudflare-dns.com, sni=cloudflare-dns.com, path=/dns-query, post=true, fragment=true

[Proxy]
direct = direct
block = reject
fragment = fragment, fragment=true

[Proxy Group]
proxy = chain, fragment, direct

[Rule]
NETWORK, UDP, direct
EXTERNAL, site:category-ads-all, block
GEOIP, ir, direct

FINAL, proxy